### ISSUE TITLE
enableRotation is not useful

### ISSUE THREAD

**Issue by LZS1991** [openlayers/ol-cesium#447] opened 2017-02-28 16:03 UTC
I set enableRotation in the View to be false,but when i  rotate in the Cesium and come back,the 2D map still have rotated.So how to destroy the  synchronization of rotatoin between 2D and 3D map?Thank you for any answer!

**Comment by gberaudo** [comment] 2017-03-02 16:49
Indeed it is not possible at the moment. Closing as a duplicate of https://github.com/openlayers/ol-cesium/issues/436.

**Closed by gberaudo** 2017-03-02 16:49 UTC
